name: Testing only
on:
    push

jobs:
    build:
        runs-on: ubuntu-18.04
        steps:
        - uses: actions/checkout@v1
        - name: Enable experimental features in Docker
          run: |
                sudo rm -rf /etc/docker/daemon.json \
                echo '{"experimental": true}' | sudo tee -a /etc/docker/daemon.json \
                sudo systemctl restart docker
        - name: Run Build script
          run: sudo ./build-test.sh
