name: Testing only
on:
    push:
        tags: [ '*' ]

jobs:
    build:
        runs-on: ubuntu-18.04
        steps:
        - uses: actions/checkout@v1
        - name: Enable experimental features in Docker
          run: |
                sudo rm -rf /etc/docker/daemon.json
                echo '{"experimental": true}' | sudo tee -a /etc/docker/daemon.json
                sudo systemctl restart docker
        - name: Run Build script
          run: sudo ./build-test.sh
        - name: Release zip
          uses: meeDamian/github-release@2.0
          with:
            gzip: false
            files: "overlay2.tar.gz"
            token: ${{ secrets.GITHUB_TOKEN }}
            allow_override: true
