name: Run Release Script on push to MASTER
on: 
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-18.04
        steps:
        - uses: actions/checkout@v1
        - name: Install Dependencies
          run: sudo apt-get -y install quilt qemu-user-static debootstrap bsdtar
        - name: Run Build script
          run: sudo ./build.sh
        - name: Debug deploy dir
          run: ls -la deploy/
        - name: Debug current working dir
          run: ls -la
        - name: Release Image
          if: startsWith(github.ref, 'refs/tags/')
          uses: meeDamian/github-release@v1.0.0
          with:
            gzip: false
            files: deploy/*.zip
            token: ${{ secrets.GITHUB_TOKEN }}
